package Simulatuon;

import javax.swing.*;
import javax.swing.border.TitledBorder;
import java.awt.*;

public class GUIForm {
    private JPanel mainPanel;
    private JPanel controller;

    private void createUIComponents() {
        // TODO: place custom component creation code here
    }

    {
// GUI initializer generated by IntelliJ IDEA GUI Designer
// >>> IMPORTANT!! <<<
// DO NOT EDIT OR ADD ANY CODE HERE!
        $$$setupUI$$$();
    }

    /**
     * Method generated by IntelliJ IDEA GUI Designer
     * >>> IMPORTANT!! <<<
     * DO NOT edit this method OR call it in your code!
     *
     * @noinspection ALL
     */
    private void $$$setupUI$$$() {
        createUIComponents();
        mainPanel.setLayout(new BorderLayout(0, 0));
        mainPanel.setEnabled(true);
        mainPanel.setForeground(new Color(-13803077));
        mainPanel.setBorder(BorderFactory.createTitledBorder(null, "主畫面", TitledBorder.CENTER, TitledBorder.DEFAULT_POSITION, this.$$$getFont$$$(null, Font.BOLD | Font.ITALIC, 36, mainPanel.getFont()), new Color(-16729157)));
        controller = new JPanel();
        controller.setLayout(new BorderLayout(0, 0));
        mainPanel.add(controller, BorderLayout.CENTER);
        controller.setBorder(BorderFactory.createTitledBorder(null, "控制面板", TitledBorder.DEFAULT_JUSTIFICATION, TitledBorder.BOTTOM, this.$$$getFont$$$(null, Font.BOLD, -1, controller.getFont()), new Color(-65536)));
        final JLabel label1 = new JLabel();
        label1.setText("Label");
        controller.add(label1, BorderLayout.WEST);
    }

    /**
     * @noinspection ALL
     */
    private Font $$$getFont$$$(String fontName, int style, int size, Font currentFont) {
        if (currentFont == null) return null;
        String resultName;
        if (fontName == null) {
            resultName = currentFont.getName();
        } else {
            Font testFont = new Font(fontName, Font.PLAIN, 10);
            if (testFont.canDisplay('a') && testFont.canDisplay('1')) {
                resultName = fontName;
            } else {
                resultName = currentFont.getName();
            }
        }
        return new Font(resultName, style >= 0 ? style : currentFont.getStyle(), size >= 0 ? size : currentFont.getSize());
    }

    /**
     * @noinspection ALL
     */
    public JComponent $$$getRootComponent$$$() {
        return mainPanel;
    }
}
